# userMessage
POST http://localhost:8000/api/user_message
content-type: application/json

{
    "message": "I want to work today on something impactful from revenue perspective. What do you suggest?"
}

###

# get messages
GET http://localhost:8000/api/messages?conversation_id=dec4dc08-7d25-4c9a-835d-2e6e47540b17

###

# get conversations
GET http://localhost:8000/api/conversations