name: Dependency Update and Audit

on:
  schedule:
    - cron: '0 0 * * 0' # weekly

jobs:
  update-and-audit:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Update dependencies
      run: npm update

    - name: Run audit
      run: npm audit

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add package-lock.json
        git commit -m "Update dependencies and run audit"

    - name: Push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: git push

