name: Virtual Office Pet ORIGINAL

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install dependencies
      working-directory: ./virtual-office-pet
      run: |
        if [ -f package-lock.json ]; then
          npm ci
        else
          npm install
        fi

    - name: Build
      run: SKIP_PREFLIGHT_CHECK=true npm run build --if-present --no-audit 2>&1 | tee build.log; test ${PIPESTATUS} -eq 0
      working-directory: ./virtual-office-pet

    - name: Login to GitHub Packages Docker registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./virtual-office-pet
        push: true
        tags: ghcr.io/${{ github.repository }}/virtual-office-pet:original    

    - name: 'Az CLI login'
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Deploy Container App
      uses: azure/container-apps-deploy-action@v1
      with:
        registryUrl: ghcr.io
        containerAppName: virtual-office-pet-original
        resourceGroup: rg-ai-team-qcga
        imageToDeploy: ghcr.io/${{ github.repository }}/virtual-office-pet:original
        targetPort: 80
        ingress: external