name: Virtual Office Pet

on:
  workflow_dispatch:
  push:
    paths:
      - 'virtual-office-pet/**'
    branches: [ main ]
  pull_request:
    paths:
      - 'virtual-office-pet/**'
    branches: [ main ]

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install dependencies
      working-directory: ./virtual-office-pet
      run: |
        if [ -f package-lock.json ]; then
          npm ci
        else
          npm install
        fi

    - name: Build
      run: SKIP_PREFLIGHT_CHECK=true npm run build --if-present --no-audit 2>&1 | tee build.log
      working-directory: ./virtual-office-pet

    - name: Capture logs on failure
      if: failure()
      run: |
        echo "Failure detected"
        cat ./virtual-office-pet/build.log

    # - name: Test
    #   run: npm test -- --passWithNoTests
    #   working-directory: ./virtual-office-pet
    #   env:
    #     CI: true

    # - name: Lint
    #   run: npm run lint
    #   working-directory: ./virtual-office-pet

    - name: Login to GitHub Packages Docker registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./virtual-office-pet
        push: true
        tags: ghcr.io/${{ github.repository }}/virtual-office-pet:${{ github.run_id }}    

    - name: 'Az CLI login'
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Deploy Container App
      uses: azure/container-apps-deploy-action@v1
      with:
        registryUrl: ghcr.io
        containerAppName: virtual-office-pet
        resourceGroup: rg-ai-team-ccay
        imageToDeploy: ghcr.io/${{ github.repository }}/virtual-office-pet:${{ github.run_id }}
        targetPort: 80
        ingress: external

  # post-build:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   if: failure()
  #   steps:
  #   - run: ls ${{ runner.temp }}/_github_workflow/